---
name: cmpsc-100-fall-2018-lab9
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        labnine/TodoListItem.java:
            --single 1 --language Java
            --multi 15 --language Java
            --fragment "println(" --count 0 --exact
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        labnine/TodoList.java:
            --single 14 --language Java
            --multi 11 --language Java
            --fragment "while (" --count 5
            --fragment "if (" --count 4
            --fragment "ArrayList<TodoListItem>" --count 6
            --fragment "Iterator<TodoListItem>" --count 7
            --fragment "println(" --count 0 --exact
src/main:
    java:
        labnine/TodoListManager.java:
            --single 3 --language Java
            --multi 2 --language Java
            --fragment "while (" --count 3
            --fragment "if (" --count 6
            --fragment "else if (" --count 5
            --fragment "println(" --count 10
            --fragment "break" --count 1 --exact
            --fragment "TODO" --count 0 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 1 --exact
    --words 100
# --> check the number of commits beyond a threshold
--commits 10
